### ISSUE TITLE
unpack doesnt work

### ISSUE THREAD

**Issue by ryanmurray** [CaptInsano/docker-containers#13]
when trying to unpack a torrent 
in log get unrar: invalid option -- 'i'
 Try `unrar --help' or`unrar --usage' for more information.

**Comment by CaptInsano** [comment]
are you running the variable EDGE=1 to update to latest git version of rutorrent?

If not, try adding EDGE=1 to the container config page and see if it works?

**Comment by CaptInsano** [comment]
after a bit of searching I have found reports of ruTorrent not working great with unrar-free so I have changed the dockerfile to install unrar (non-free).

New version building at the mo, please report if issues persist.
